### ISSUE TITLE
Avoid using `setEncoding`

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/get-stream#10]
I think calling `setEncoding` affects the data received by other `data` listeners:

```js
var stream = someStream();
stream.on('data', chunk => assert(Buffer.isBuffer(chunk)));

// vs

var stream = someStream();
var p = getStream(stream);
stream.on('data', chunk => assert(typeof chunk === 'string'));
```

Perhaps it would be better to pipe to a PassThrough stream, and listen to that.

**Comment by kevva** [comment]
Fixed in https://github.com/sindresorhus/get-stream/commit/607623b733f85980a52d8ea89d8da0406bb700a5.
