### ISSUE TITLE
v8 release notes

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/get-stream#102]
I think we are ready to release v8.0.0, what do you think?
Here are some potential release notes that you can feel free to pick/tweak.
Note: the links to issues/PRs do not show their titles in GitHub releases, so it looks less verbose.

---

## Breaking

- Remove the `encoding` option. (#69, #67)
  - This package handles binary, UTF-8 and object streams.
  - For other encodings like UTF-16, hexacimal and base64, please see the [following tip](https://github.com/sindresorhus/get-stream#non-utf-8-encoding). (#84)
  - Methods like [`buffer.toString('hex')` or `buffer.toString('base64')`](https://nodejs.org/api/buffer.html#buftostringencoding-start-end) can also be used.

## Features

- Support any JavaScript environment, including browsers. (#85)
- Support web streams ([`ReadableStream`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream)). (#82, #78, #79, #80)
- Support [async iterables](https://github.com/sindresorhus/get-stream#async-iterables). (#69, #93)
- Add [`getStreamAsArray()`](https://github.com/ehmicky/get-stream#getstreamasarraystream-options) method to pass streams [in object mode](https://github.com/ehmicky/get-stream#getstreamasarraystream-options). (#86)
- Add [`getStreamAsArrayBuffer()`](https://github.com/sindresorhus/get-stream#getstreamasarraybufferstream-options) method to return the stream as an [`ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer). (#81)
- When the stream is larger than the maximum size for a [string](https://nodejs.org/api/buffer.html#bufferconstantsmax_string_length), [buffer or `ArrayBuffer`](https://nodejs.org/api/buffer.html#bufferconstantsmax_length), set [`error.bufferedData`](https://github.com/ehmicky/get-stream#errors) with the partially read data instead of leaving it empty. (#68, #48)

## Bug fixes

- Do not crash on big streams (with one/many GBs). (#66)
- Ensure `maxBuffer` stops infinite streams. (#62)
- Stop consuming the streaming when hitting [`maxBuffer`](https://github.com/ehmicky/get-stream#maxbuffer). (#42, #69).
- Set [`error.bufferedData`](https://github.com/ehmicky/get-stream#errors) when the stream errors for other reasons than [`maxBuffer`](https://github.com/ehmicky/get-stream#maxbuffer). (#56, #63)
- Ensure [`error.bufferedData`](https://github.com/ehmicky/get-stream#errors) is smaller than [`maxBuffer`](https://github.com/ehmicky/get-stream#maxbuffer). (#89)

## TypeScript Types

- The `stream` argument must be a [`Readable`, `ReadableStream` or `AsyncIterable`](https://github.com/sindresorhus/get-stream/blob/c1df6e8f3a52885489f0120d3c5e55d4f49d9d44/source/index.d.ts#L10). (#71)

## Documentation

- Add tips on [alternatives](https://github.com/sindresorhus/get-stream#alternatives), [`Blob`](https://github.com/sindresorhus/get-stream/tree/main#blobs) and [JSON streaming](https://github.com/sindresorhus/get-stream/tree/main#json-streaming).  (#58, #95, #96, #97)

## Performance

- Do not block the event loop when the stream ends. (#92)
- Add [benchmarks](https://github.com/ehmicky/get-stream#benchmarks). (#94)

**Comment by sindresorhus** [comment]
Done: https://github.com/sindresorhus/get-stream/releases/tag/v8.0.0

Thank you so much for your great work with this release. This package is just so much better now in every way. 🎉

Are you interested in being added as a maintainer? No worries if not.

**Comment by ehmicky** [comment]
Thanks for the kind words @sindresorhus!
Those PRs were lots of fun.
Yes, absolutely, I would be interested, I had already starting watching the repository for new issues posting :)

**Comment by sindresorhus** [comment]
Awesome 👍

**Comment by ehmicky** [comment]
:clap:
