### ISSUE TITLE
Incompatibility with ESLint rule import/no-unresolved

### ISSUE THREAD

**Issue by bershanskiy** [sindresorhus/get-stream#109]
ESLint rule `import/no-unresolved` fails to resolve `get-stream` version 8 because this rule does supports only `package.json` key `main` but not `exports` and `get-stream` provides only `exports` and does not provide `main`.

As a fix, I propose adding the following line to `get-stream`'s `package.json`:
```json
"main": "source/index.js",
```

I'll look into extending this ESLint rule with `exports` support, but that is likely to take a while.

**Comment by bershanskiy** [comment]
Most packages do not need to have `main` specified explicitly, since most of them use the [default entry point `index.js`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#main). `get-stream` uses the non-default location, so it probably should explicitly specify it for compatibility.

**Comment by ehmicky** [comment]
Hi @bershanskiy,

Thanks for the additional insights. @sindresorhus What do you think considering the additional information about `import/no-unresolved`?

**Comment by sindresorhus** [comment]
> ESLint rule import/no-unresolved fails to resolve get-stream version 8 because this rule does supports only package.json key main but not exports and get-stream provides only exports and does not provide main.

That is a problem with `import/no-unresolved` and you need to bring it up there.

**Comment by sindresorhus** [comment]
`exports` is a modern replacement to `main`. We are not going to bring back `main`.

https://nodejs.org/api/packages.html#package-entry-points

**Comment by ehmicky** [comment]
For reference, the issue you might want to track seems to be this one: https://github.com/import-js/eslint-plugin-import/issues/2495
