### ISSUE TITLE
Package is empty

### ISSUE THREAD

**Issue by Gradlon** [sindresorhus/get-stream#113]
The Package is empty.
Only the Source files are present.

**Comment by sindresorhus** [comment]
It installs fine for me. Probably an issue with npm or your system.

**Comment by wowczarczyk** [comment]
@sindresorhus  I think the problem is with no "main" attribute in package.json, I am using pnpm and it seems to be an issue with this bundler, after adding it everything works fine

**Comment by sindresorhus** [comment]
That's a problem with your bundler, not this package.

**Comment by wowczarczyk** [comment]
I think this might be a problem with my `tsconfig`, saw another Issue where it was stated that `moduleResolution` of "NodeNext" should fix the problem, but for me it didn't...
