### ISSUE TITLE
Cannot find module 'get-stream' or its corresponding type declarations. -> Missing TS types?

### ISSUE THREAD

**Issue by sebastianrueckerai** [sindresorhus/get-stream#114]
Hi!

I am using your awesome package in my firebase functions project in TypeScript.
For me `import getStream from "get-stream"` gives the following error:
 `Cannot find module 'get-stream' or its corresponding type declarations.`
 
 I think this might be because TS type declarations are missing? 
 
 When I was still writing in pure JS, `const getStream = require("get-stream")` worked fine, but I cant use it in my current project.
 
 In any case, any help would be welcome!
 
 Cheers!

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by sebastianrueckerai** [comment]
Hi thanks for the link @sindresorhus !

My project is set up for ESM in the way your linked document describes.
I am also using the `"import x from "x"``syntax. The one package giving me trouble is `get-stream` with this warning:
`Cannot find module 'get-stream' or its corresponding type declarations.ts(2307)`

I had the same with other packages and solved it by installing TS types, e. g.: `"@types/svg-to-pdfkit": "^0.1.3",`

Ignoring the warning for `get-stream leads to this error when compiling to JS:
src/handlers/progress.ts:14:23 - error TS2307: Cannot find module 'get-stream' or its corresponding type declarations.

I am no TS expert yet, but my interpretation as that this is because `get-stream` is missing type files. Is there something I am missing? Some other way of making this work? Any help would be greatly appreciated.

Additional Info:
User
This is my node version:
`v20.10.0`

This is my tsconfig:
```
{
  "compilerOptions": {
    "allowJs": true,
    "module": "esnext", // Changed to 'esnext' for ESM support
    "moduleResolution": "node", // Node-style module resolution
    "esModuleInterop": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "rootDir": "./src",
    "outDir": "./lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2022", // Ensure compatibility with ES2022 features
    "types": ["jest"],
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"],
}
```

Here is my package.json:
```
{
  "name": "functions",
  "exports": "./index.js",
  "type": "module",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log",
    "test": "jest --config jest.config.js",
    "clean": "rimraf ./lib",
    "build": "npm run clean && tsc",
    "buildlint": "npm run clean && npm run lint && tsc",
    "lint": "eslint . --ext .js,.ts",
    "postinstall": "patch-package"
  },
  "engines": {
    "node": "20"
  },
  "dependencies": {
    "@aws-sdk/client-cloudfront": "^3.496.0",
    //...
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "@jest/globals": "^29.7.0",
    "@types/archiver": "^6.0.2",
    //...
    "get-stream": "^8.0.1",
    //... 
    "typescript": "^5.3.3"
  },
  "private": true
}
```

**Comment by sindresorhus** [comment]
> "moduleResolution": "node",

This must be `exnext` too.

**Comment by electic** [comment]
> > "moduleResolution": "node",
> 
> This must be `esnext` too.
<img width="206" alt="Screenshot 2024-03-26 at 3 59 45 AM" src="https://github.com/sindresorhus/get-stream/assets/43028/66d27138-f9e6-4599-b034-b4f4d0ebfa41">


Having the same issue. This is not a valid option for moduleResolution.

**Comment by n14s** [comment]
Had the same problem.

This line of [the link of sindresorhus answer](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) solved it for me

``` quote
Use only full relative file paths for imports: import x from '.'; → import x from './index.js';.
```
