### ISSUE TITLE
Allow multiple readers at once

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/get-stream#119]
When `get-stream` is used, other readers cannot be used at the same time. 

For example, this does not work (both calls will compete for the same data):

```js
await Promise.all([
  getStream(stream),
  getStream(stream),
])
```

This creates some limitations for users. For example, in Execa, the following does not work:

```js
import {execa} from 'execa'

const subprocess = execa(...)
subprocess.stdout.on('data', chunk => {...})
const {stdout} = await subprocess
```

Because the `data` event and the `stdout` buffering compete for the same data. Users have to opt-out of `stdout` buffering by using the `buffer: false` option.

However, it does not have the be this way. The issue here is that `get-stream` uses [`Readable[Symbol.asyncIterator]`](https://github.com/nodejs/node/blob/4c3e9659ed116e610d8da8aa0b692cc8c6abb6e4/lib/internal/streams/readable.js#L1336). The default implementation relies on calling [`stream.read()`](https://github.com/nodejs/node/blob/4c3e9659ed116e610d8da8aa0b692cc8c6abb6e4/lib/internal/streams/readable.js#L1380) repeatedly. This works but does not allow for multiple readers at once.

Instead, using `stream.on('data')` would allow for multiple readers at once. We should make `get-stream` use that instead. 

Since `get-stream` supports not only Node.js `Readable` streams but any async iterable, this logic would only be used when a Node.js `Readable` stream is passed.

**Comment by sindresorhus** [comment]
👍

**Comment by sindresorhus** [comment]
> uses [Readable[Symbol.asyncIterator]](https://github.com/nodejs/node/blob/4c3e9659ed116e610d8da8aa0b692cc8c6abb6e4/lib/internal/streams/readable.js#L1336). The default implementation relies on calling [stream.read()](https://github.com/nodejs/node/blob/4c3e9659ed116e610d8da8aa0b692cc8c6abb6e4/lib/internal/streams/readable.js#L1380) repeatedly. This works but does not allow for multiple readers at once.

Worth opening a Node.js issue about this?

**Comment by ehmicky** [comment]
https://github.com/nodejs/node/issues/52086
