### ISSUE TITLE
ES6 code cannot be minified by webpack

### ISSUE THREAD

**Issue by dvdsgl** [sindresorhus/get-stream#20]
My project uses `get-stream` via transitive dependency, so now I cannot deploy my app because [webpack chokes on ES6](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify). It's still recommended to publish ES5 on `npm`.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
