### ISSUE TITLE
Pre-compiled npm package

### ISSUE THREAD

**Issue by sergeymishin** [sindresorhus/get-stream#22]
I'm getting an error building my react app with your package.
[more about this issue](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)
Can you please publish a pre-compiled package?
Thanks!

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.
