### ISSUE TITLE
use end-of-stream instead of end event?

### ISSUE THREAD

**Issue by contra** [sindresorhus/get-stream#23]
there's a lot of complexity with finding a stream end, this library looks like it just listens for the `end` event which is not the case for many streams. specifically having an issue where `destroy` being called on a stream will leave `get-stream` waiting forever even though the stream is done.

using https://github.com/mafintosh/end-of-stream should fix this problem and make this library more adept with stream ends

if interested, i can send a PR

**Comment by sindresorhus** [comment]
👍
