### ISSUE TITLE
use readable-stream in the browser

### ISSUE THREAD

**Issue by hugomrdias** [sindresorhus/get-stream#27]
would you consider a PR to alias `'stream': 'readable-stream'` only for the browser? This way we don't rely on bundlers choosing the polyfill, also webpack 5 will stop doing so.

**Comment by sindresorhus** [comment]
Sorry, no. That would make it a dependency for Node.js. Something I don't want.

**Comment by sindresorhus** [comment]
> also webpack 5 will stop doing so.

That's not final yet.

**Comment by hugomrdias** [comment]
a dependency for node ? it would be in the package.json yes but node would still run `require('stream')` if we do 

```json
"browser": {
    "stream": "readable-stream"
},
```

**Comment by sindresorhus** [comment]
Yes, but it would have to be in the `dependencies` field, which means Node.js users would have to install and waste space on it.

**Comment by hugomrdias** [comment]
imo being browser friendly is worth the extra bytes, but i understand. ty

**Comment by ehmicky** [comment]
`ReadableStream` is not supported in the latest version of this package. (#82).
