### ISSUE TITLE
v5 TypeScript typings incompatible with v4

### ISSUE THREAD

**Issue by grantila** [sindresorhus/get-stream#29]
One could previously

```ts
import { buffer as getStreamAsBuffer } from 'get-stream'
```

but in 5.0, `buffer` and `array` aren't exported, only available on the default export (which is not the same thing), so one *must*

```ts
import temporary from 'get-stream'
const getStreamAsBuffer = temporary.buffer
```

**Comment by sindresorhus** [comment]
That was an intentional change. I'm not interested in changing it or adding multiple ways to use this module.

You don't do this:

```js
import temporary from 'get-stream'
const getStreamAsBuffer = temporary.buffer
```

You just use it like this:

```js
import getStream from 'get-stream'
getStream.buffer()
```

**Comment by grantila** [comment]
I used the word `temporary` intentionally to make it clear that I _have_ to import something I don't care about, namely a function which returns a string. Everyone using this package must know about that function to be able to use other functions _attached_ on it.

This old-school way of using functions as namespaces is kind of hackish IMO, and is badly aligned with modern ES modules, where you only import what you want.

But it's your call surely.
