### ISSUE TITLE
Use `stream.pipeline` and `stream.finished` when targeting Node.js 10

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/get-stream#33]
I think we could get rid of the `pump` dependency then, and probably simplify the codebase considerably.

**Comment by szmarczak** [comment]
I think it can be done now.

**Comment by sindresorhus** [comment]
Yes

**Comment by tiagonapoli** [comment]
I would like very much to open a PR for this!

**Comment by tiagonapoli** [comment]
@sindresorhus @szmarczak Opened a PR for this :) https://github.com/sindresorhus/get-stream/pull/39

**Comment by sindresorhus** [comment]
Fixed by #39
