### ISSUE TITLE
Add a `maxBuffer` option

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/get-stream#8]
See https://github.com/sindresorhus/execa/issues/33

**Comment by sindresorhus** [comment]
👍  I assume you want an error thrown when it reaches the maximum. For the array method, maybe it should count array items instead of bytes?

**Comment by jamestalmage** [comment]
My thought was that if you set maxBuffer, every item passed in must have a numeric `length` property.

Maybe a `maxItems` option, only for arrays? That way you can still use maxBuffer for arrays if there is a length property

**Comment by sindresorhus** [comment]
Ok, so how about this; We do the same for all the methods and limit on the total byte size, but if it's an object stream (accepted in `.array()`), we follow the stream `highWaterMark` option and work on items, not on byte size.

**Comment by sindresorhus** [comment]
> When in objectMode, streams can push Strings and Buffers as well as any other JavaScript object. Another major difference is that when in objectMode, the internal buffering algorithm counts objects rather than bytes. This means if we have a Transform stream with the highWaterMark option set to 5, the stream will only buffer a maximum of 5 objects internally. - https://nodesource.com/blog/understanding-object-streams/

**Comment by sindresorhus** [comment]
Sidenote: Object streams feels very similar to Observables, although with back-pressure support and no utility methods.

**Comment by jamestalmage** [comment]
Re: Observables

Yep, that's it essentially.

**Comment by jamestalmage** [comment]
A stream of strings is still in objectMode though (I believe). So you couldn't do:

```js
getStream(stream.pipe (split())

**Comment by sindresorhus** [comment]
Are you sure? I don't see any `objectMode` reference here: https://github.com/dominictarr/split/blob/master/index.js

**Comment by jamestalmage** [comment]
No. Definitely not sure.

**Comment by jamestalmage** [comment]
From the article:

> If an object stream *isn't* emitting Strings or Buffers, it's important to note that you can't pipe it to a non-object stream.

So it looks like maybe `objectMode` is taken into account on the stream you are piping to?

So if I'm setting up a transform stream that takes in Strings/Buffers and emits Objects, is that not an ObjectMode stream (because it doesn't **take** objects)? I think that's what I'm reading.

**Comment by kevva** [comment]
> So if I'm setting up a transform stream that takes in Strings/Buffers and emits Objects, is that not an ObjectMode stream (because it doesn't take objects)? I think that's what I'm reading.

Yup, I think only the receiving one needs to be.

**Comment by jamestalmage** [comment]
https://github.com/jamestalmage2/stream-objectmode-tests

That turned out to have a few surprises.

**Comment by sindresorhus** [comment]
@jamestalmage That's useful info! You should submit a link to the repo to https://github.com/stephenplusplus/stream-faqs ;)
